### ISSUE TITLE
Установка

### ISSUE THREAD

**Issue by Alextoday** [pavel-hushcha/Uschedule_bot#1]
Здравствуйте, во первых спасибо за Вашу работу, очень крутая !))
 Можно гайд для новичков, как установить на хостинге Ваш бот?)

**Comment by pavel-hushcha** [comment]
Здравствуйте, спасибо.
Для размещения бота основной критерий был бесплатность, так как это по сути pet-проект. Поэтому сам бот был размещен на платформе heroku (легко гуглится по запросу бесплатный телеграм бот на heroku, например). База данный размещена на Amazon RDS (бесплатно в течение года, также легко гуглится). Если будут проблемы - спрашивайте.

**Comment by Alextoday** [comment]
Благодарю за отзывчивость, буду разбираться)

**Comment by Alextoday** [comment]
А можете, пожалуйста, подсказать,  если не сложно, как правильно БД настроить, сделал postgresql в Amazon RDS, как законнектить правильно? С остальным разобрался..

**Comment by pavel-hushcha** [comment]
> А можете, пожалуйста, подсказать, если не сложно, как правильно БД настроить, сделал postgresql в Amazon RDS, как законнектить правильно? С остальным разобрался..

Здесь подробно описано https://aws.amazon.com/ru/getting-started/hands-on/create-connect-postgresql-db/
Откуда присоединяться будете?
